### ISSUE TITLE
Software update architecture update

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#58]
For each version update:
1. Individual database
2. Individual jar file
3. Shared static image file, make sure images are compatible per version

**Comment by cyokin** [comment]
Here is the plan
- clone database for each release, rename old DB name as tend_0.0.6(example) when have any DB changes, so that we can easily rollback to old version. 
- each release will have individual jar file, keep the old file for rollback.  
- image file name is uuid format, it will compatible all persons.
